# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Paolo Bernasconi
tagline:          Personal Blog
url:              http://paolobernasconi.com
paginate:         3
paginate_path:    "blog/page:num/"
baseurl:          /
blogurl:          /blog/
author:
  name:           Paolo Bernasconi
  url:            https://twitter.com/paolobernasconi
  email:          paolo.enrico.bernasconi@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/pbernasconi/paolobernasconi.github.io
