# Build settings
markdown: redcarpet
highlighter: pygments
permalink: pretty

title: "Paolo Bernasconi"
description: > # this means to ignore newlines until "email:"
email: paolo.enrico.bernasconi@gmail.com
logo: "/assets/images/pb_logo.png"


name: 'Paolo Bernasconi'
author: 'Paolo Bernasconi'
author_image: "/assets/images/author.jpeg"

paginate:	5

url: "http://paolobernasconi.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/paolobernasconi
    desc:   Follow me on twitter

  - icon:	github
    url:	https://github.com/pbernasconi
    desc:	Fork me on github

  - icon:	linkedin
    url:	https://www.linkedin.com/in/paolobernasconi
